name: EmptyWorld
main: aliuly\emptyworld\Main
version: 1.1.0
api: 2.0.0
description: An empty world generator
author: aliuly
load: STARTUP
website: https://github.com/Muirfield/pocketmine-plugins/tree/master/EmptyWorld
