name: SignWarp
api: [1.10.0,1.12.0,2.0.0]
version: 1.6.0
load: POSTWORLD
main: aliuly\signwarp\Main
author: aliuly
softdepend: [FastTransfer,WorldProtect]
website: https://github.com/Muirfield/pocketmine-plugins/tree/master/SignWarp

permissions:
  signwarp.place.sign:
    default: op
    description: "Allow user to create warp"
  signwarp.touch.sign:
    default: true
    description: "Allow user to use warp"
  signwarp.place.transfer.sign:
    default: op
    description: "Allow user to create transfer signs"
  signwarp.touch.transfer.sign:
    default: true
    description: "Allow user to use transfer signs"
  signwarp.cmd.xyz:
    default: true
    description: "Shows current x,y,z coordinates"
