name: WEdit
main: WEdit\WEdit_main
version: 2.3.0
api: [1.0.0]
load: STARTUP
author: Gonbe34
authors: [Gonbe34]
description: The new world editor for 1.5
website: http://mcpe.mods.jp/blog/
commands:
 /set:
  description: set the specific block at registered coordinate.
  usage: "/set <id> : 範囲をブロックで埋めます"
  permission: wedit.command
 /cut:
  description: cut block at registered coordinate.
  usage: "/cut : 範囲のブロックを削除します"
  permission: wedit.command
 /replace:
  description: replace block at registered coordinate.
  usage: "/replace <ID1> <ID2> : ID1をID2のブロックに置き代えます"
  permission: wedit.command
 /air:
  description: replace to air block at registered coordinate.
  usage: "/air <id> : IDのブロックのみ削除します"
  permission: wedit.command
 /undo:
  description: undo
  usage: "/undo : 前回の操作を取り消します"
  permission: wedit.command
 /e:
  description: erase position data
  usage: "/e [1|2]: 指定する場合片方を、指定しない場合POS1とPOS2の両方の範囲データを削除します。"
  permission: wedit.command
 /help:
  description: show usage
  usage: "/help or / "
  permission: wedit.command
 /pos:
  description: set coordinate by command
  usage: "/pos [1|2] <x> <y> <z> : 座標データをコマンドで設定します。"
  permission: wedit.command
 /:
  description: show usage
  usage: "/help or /"
  permission: wedit.command
 /copy:
  description: copy the area
  usage: "/copy 選択範囲をコピーします"
  permission: wedit.command
 /paste:
  description: paste things into the area
  usage: "/paste 選択範囲をペーストします"
  permission: wedit.command
 /input:
  description: 
  usage: "/paste "
  permission: wedit.command
 /output:
  description: 
  usage: "/paste "
  permission: wedit.command
permissions:
 wedit:
  default: op
  description: "permittion that allows player to use WEdit"
  children:
   wedit.command:
    default: op
    description: "permittion that allows player to use WEdit"
