name: PermissionPlus
main: PermissionPlus\PermissionPlus
version: 1.5.4
api: [1.12.0]
load: STARTUP
author: Hmy2001
authors: [Hmy2001]
description: PermissionPlus.
commands:
 pp:
  aliases: [pp]
  description: PermissionPlus help
 ppplayer:
  aliases: [ppplyr]
  description: Manages player permission
 ppcommand:
  aliases: [ppcmd]
  description: Manages player permission
 ppsub:
  description: PermissionPlus preferences
 ppconfig:
  aliases: [ppcfg]
  description: PermissionPlus preferences